version: "3.8"

services:
  app:
    image: 'jazzdoit/marketplace:latest'
    build:
      context: .
    container_name: 'app'
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    environment:
      - 'SPRING_PROFILES_ACTIVE=dev'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/marketplace_local
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: 'db'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=12345'
      - 'POSTGRES_DB=marketplace_local'
volumes:
  postgres-data: